# Generated by Django 3.1.1 on 2020-10-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayhomerecord',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
