# Generated by Django 3.1.1 on 2020-10-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201019_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayhomerecord',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='static/media/docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='stayhomerecord',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='stayhomerecord',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='static/media/videos/%Y/%m/%d/'),
        ),
    ]
