# Generated by Django 3.1.1 on 2020-10-05 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_contact_location_record_researcher_tracer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stayhomerecord',
            name='documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stayhomerecord',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stayhomerecord',
            name='location',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='stayhomerecord',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
