# Generated by Django 3.1.1 on 2020-10-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201005_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='relate',
        ),
    ]
